sudo: required
services:
  - docker

before_install:
  - docker build -t digitalbrick/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run digitalbrick/react-test npm run test -- --watchAll=false --coverage

after_success:
  - docker build -t digitalbrick/multi-client ./client
  - docker build -t digitalbrick/multi-nginx ./nginx
  - docker build -t digitalbrick/multi-server ./server
  - docker build -t digitalbrick/multi-worker ./worker

#login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push digitalbrick/multi-client
  - docker push digitalbrick/multi-nginx
  - docker push digitalbrick/multi-server
  - docker push digitalbrick/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-west-1"
#  app: "docker-react"
#  env: "Dockerreact-env-1"
#  bucket_name: "elasticbeanstalk-eu-west-1-998901271422"
#  bucker_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
